spring:
  datasource:
    url: jdbc:mysql:mysql://root:DiUrZHbtUvzPtJOZshwxMaTEqiSaExhH@autorack.proxy.rlwy.net:22216/railway
    username: root
    password: DiUrZHbtUvzPtJOZshwxMaTEqiSaExhH
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: 1tihuygay@gmail.com
    password: kepk uyox btrk dizo
    protocol: smtp
    sender:
      email: 1tihuygay@gmail.com
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.debug: true
server:
  port: ${PORT:8080}

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.mail.javamail: DEBUG
    root: INFO
    org.springframework.security: DEBUG
    com.alibou.security: DEBUG
    org.springframework.web: DEBUG
